### ISSUE TITLE
Ignore Sails Blueprint routes.

### ISSUE THREAD

**Issue by Kawirider636** [theo4u/sails-hook-swagger-generator#2]
I can't find a way to ignore sails blueprint routes. Blueprints are disabled in the blueprint config file but they still appear in the swagger.json. I tried sails-swagger and it does ignore the blue print routes but it has a whole slew of other problems. So I'm curious if there is a way to not include the blueprint routes in the swagger.json. 

For example, I have POST /api/0.1/user in my route.js file. I get that in the swagger.json but then i also get sails POST /user. 

Thanks for any help.

**Comment by theo4u** [comment]
oh ok,  would look into it now, to make it use the config instead to enable or disable default routes

**Comment by gabeklavans** [comment]
Has this feature been removed since then? I seem to have the same problem with the current version and I can't immediately find the fix listed here in the current codebase

**Comment by danielsharvey** [comment]
@gabeklavans What feature are you looking for specifically? This hook now listens to the `router:bind` events to determine routes to add - this means that if blueprint routes are disabled they will not appear in the Swagger. What behaviour are you observing?

**Comment by gabeklavans** [comment]
@danielsharvey I have an action in my app named `<controller>/remove` which matches one of the sails blueprint actions, so I disabled blueprints in sails using `rest = false` and all that.

However, when I generate the swagger.json, it adds parameters I didn’t define to that route that throw “not found in path” errors, like “association” and “childId” (which I assume are due to the blueprint matching).

The workaround I used for this was to set this configuration
`updateBlueprintActionTemplates: () => 'RndmString'`
but this seems kinda hacky and I’m not sure if it’s doing exactly what I think it is. It does however prevent the generator from adding those parameters that don’t exist.

I’m not certain but it seems like the same problem @Kawirider636 had

**Comment by danielsharvey** [comment]
@gabeklavans Thanks, I understand. 

In your case, where you have disabled blueprints completely (`rest = false`) you can remove the blueprint templates as follows:
```
updateBlueprintActionTemplates: () => {}
```

It sounds like there is also a case for a per-action (or per-model) configuration like:
```
blueprint: false
```
which does skips application of the blueprint template for that specific item.
